/* Autogenerated from the list of modules */
#include <unistd.h>
int libvlc_errmsg(void);
int libvlc_clearerr(void);
int libvlc_printerr(void);
int libvlc_vprinterr(void);
int libvlc_add_intf(void);
int libvlc_audio_equalizer_get_amp_at_index(void);
int libvlc_audio_equalizer_get_band_count(void);
int libvlc_audio_equalizer_get_band_frequency(void);
int libvlc_audio_equalizer_get_preamp(void);
int libvlc_audio_equalizer_get_preset_count(void);
int libvlc_audio_equalizer_get_preset_name(void);
int libvlc_audio_equalizer_new(void);
int libvlc_audio_equalizer_new_from_preset(void);
int libvlc_audio_equalizer_release(void);
int libvlc_audio_equalizer_set_amp_at_index(void);
int libvlc_audio_equalizer_set_preamp(void);
int libvlc_audio_output_device_count(void);
int libvlc_audio_output_device_get(void);
int libvlc_audio_output_device_enum(void);
int libvlc_audio_output_device_id(void);
int libvlc_audio_output_device_list_get(void);
int libvlc_audio_output_device_list_release(void);
int libvlc_audio_output_device_longname(void);
int libvlc_audio_output_device_set(void);
int libvlc_audio_output_get_device_type(void);
int libvlc_audio_output_list_get(void);
int libvlc_audio_output_list_release(void);
int libvlc_audio_output_set(void);
int libvlc_audio_output_set_device_type(void);
int libvlc_audio_get_channel(void);
int libvlc_audio_get_delay(void);
int libvlc_audio_get_mute(void);
int libvlc_audio_get_track(void);
int libvlc_audio_get_track_count(void);
int libvlc_audio_get_track_description(void);
int libvlc_audio_get_volume(void);
int libvlc_audio_set_channel(void);
int libvlc_audio_set_delay(void);
int libvlc_audio_set_mute(void);
int libvlc_audio_set_track(void);
int libvlc_audio_set_volume(void);
int libvlc_audio_toggle_mute(void);
int libvlc_audio_set_format(void);
int libvlc_audio_set_format_callbacks(void);
int libvlc_audio_set_callbacks(void);
int libvlc_audio_set_volume_callback(void);
int libvlc_chapter_descriptions_release(void);
int libvlc_clock(void);
int libvlc_dialog_dismiss(void);
int libvlc_dialog_get_context(void);
int libvlc_dialog_post_action(void);
int libvlc_dialog_post_login(void);
int libvlc_dialog_set_callbacks(void);
int libvlc_dialog_set_context(void);
int libvlc_event_attach(void);
int libvlc_event_detach(void);
int libvlc_event_type_name(void);
int libvlc_free(void);
int libvlc_get_changeset(void);
int libvlc_get_compiler(void);
int libvlc_get_fullscreen(void);
int libvlc_get_input_thread(void);
int libvlc_get_log_verbosity(void);
int libvlc_get_version(void);
int libvlc_log_get_context(void);
int libvlc_log_get_object(void);
int libvlc_log_set(void);
int libvlc_log_set_file(void);
int libvlc_log_unset(void);
int libvlc_log_clear(void);
int libvlc_log_close(void);
int libvlc_log_count(void);
int libvlc_log_get_iterator(void);
int libvlc_log_iterator_free(void);
int libvlc_log_iterator_has_next(void);
int libvlc_log_iterator_next(void);
int libvlc_log_open(void);
int libvlc_media_add_option(void);
int libvlc_media_add_option_flag(void);
int libvlc_media_discoverer_event_manager(void);
int libvlc_media_discoverer_is_running(void);
int libvlc_media_discoverer_localized_name(void);
int libvlc_media_discoverer_media_list(void);
int libvlc_media_discoverer_new(void);
int libvlc_media_discoverer_new_from_name(void);
int libvlc_media_discoverer_release(void);
int libvlc_media_discoverer_list_get(void);
int libvlc_media_discoverer_list_release(void);
int libvlc_media_discoverer_start(void);
int libvlc_media_discoverer_stop(void);
int libvlc_media_duplicate(void);
int libvlc_media_event_manager(void);
int libvlc_media_get_codec_description(void);
int libvlc_media_get_duration(void);
int libvlc_media_get_meta(void);
int libvlc_media_get_mrl(void);
int libvlc_media_get_state(void);
int libvlc_media_get_stats(void);
int libvlc_media_get_type(void);
int libvlc_media_get_user_data(void);
int libvlc_media_get_tracks_info(void);
int libvlc_media_is_parsed(void);
int libvlc_media_get_parsed_status(void);
int libvlc_media_library_load(void);
int libvlc_media_library_media_list(void);
int libvlc_media_library_new(void);
int libvlc_media_library_release(void);
int libvlc_media_library_retain(void);
int libvlc_media_list_add_file_content(void);
int libvlc_media_list_add_media(void);
int libvlc_media_list_count(void);
int libvlc_media_list_event_manager(void);
int libvlc_media_list_index_of_item(void);
int libvlc_media_list_insert_media(void);
int libvlc_media_list_is_readonly(void);
int libvlc_media_list_item_at_index(void);
int libvlc_media_list_lock(void);
int libvlc_media_list_media(void);
int libvlc_media_list_new(void);
int libvlc_media_list_player_event_manager(void);
int libvlc_media_list_player_get_media_player(void);
int libvlc_media_list_player_get_state(void);
int libvlc_media_list_player_is_playing(void);
int libvlc_media_list_player_new(void);
int libvlc_media_list_player_next(void);
int libvlc_media_list_player_pause(void);
int libvlc_media_list_player_play(void);
int libvlc_media_list_player_play_item(void);
int libvlc_media_list_player_play_item_at_index(void);
int libvlc_media_list_player_previous(void);
int libvlc_media_list_player_release(void);
int libvlc_media_list_player_retain(void);
int libvlc_media_list_player_set_media_list(void);
int libvlc_media_list_player_set_media_player(void);
int libvlc_media_list_player_set_playback_mode(void);
int libvlc_media_list_player_stop(void);
int libvlc_media_list_release(void);
int libvlc_media_list_remove_index(void);
int libvlc_media_list_retain(void);
int libvlc_media_list_set_media(void);
int libvlc_media_list_unlock(void);
int libvlc_media_new_callbacks(void);
int libvlc_media_new_fd(void);
int libvlc_media_new_location(void);
int libvlc_media_new_path(void);
int libvlc_media_new_as_node(void);
int libvlc_media_new_from_input_item(void);
int libvlc_media_parse(void);
int libvlc_media_parse_async(void);
int libvlc_media_parse_with_options(void);
int libvlc_media_parse_stop(void);
int libvlc_media_player_add_slave(void);
int libvlc_media_player_can_pause(void);
int libvlc_media_player_program_scrambled(void);
int libvlc_media_player_next_frame(void);
int libvlc_media_player_event_manager(void);
int libvlc_media_player_get_agl(void);
int libvlc_media_player_get_chapter(void);
int libvlc_media_player_get_chapter_count(void);
int libvlc_media_player_get_chapter_count_for_title(void);
int libvlc_media_player_get_fps(void);
int libvlc_media_player_get_full_chapter_descriptions(void);
int libvlc_media_player_get_full_title_descriptions(void);
int libvlc_media_player_get_hwnd(void);
int libvlc_media_player_get_length(void);
int libvlc_media_player_get_media(void);
int libvlc_media_player_get_nsobject(void);
int libvlc_media_player_get_position(void);
int libvlc_media_player_get_rate(void);
int libvlc_media_player_get_role(void);
int libvlc_media_player_get_state(void);
int libvlc_media_player_get_time(void);
int libvlc_media_player_get_title(void);
int libvlc_media_player_get_title_count(void);
int libvlc_media_player_get_xwindow(void);
int libvlc_media_player_has_vout(void);
int libvlc_media_player_is_seekable(void);
int libvlc_media_player_is_playing(void);
int libvlc_media_player_new(void);
int libvlc_media_player_new_from_media(void);
int libvlc_media_player_next_chapter(void);
int libvlc_media_player_set_pause(void);
int libvlc_media_player_pause(void);
int libvlc_media_player_play(void);
int libvlc_media_player_previous_chapter(void);
int libvlc_media_player_release(void);
int libvlc_media_player_retain(void);
int libvlc_media_player_set_agl(void);
int libvlc_media_player_set_android_context(void);
int libvlc_media_player_set_chapter(void);
int libvlc_media_player_set_equalizer(void);
int libvlc_media_player_set_evas_object(void);
int libvlc_media_player_set_hwnd(void);
int libvlc_media_player_set_media(void);
int libvlc_media_player_set_nsobject(void);
int libvlc_media_player_set_position(void);
int libvlc_media_player_set_rate(void);
int libvlc_media_player_set_role(void);
int libvlc_media_player_set_time(void);
int libvlc_media_player_set_title(void);
int libvlc_media_player_set_xwindow(void);
int libvlc_media_player_stop(void);
int libvlc_media_player_will_play(void);
int libvlc_media_player_navigate(void);
int libvlc_media_player_set_video_title_display(void);
int libvlc_media_release(void);
int libvlc_media_retain(void);
int libvlc_media_save_meta(void);
int libvlc_media_slaves_add(void);
int libvlc_media_slaves_clear(void);
int libvlc_media_slaves_get(void);
int libvlc_media_slaves_release(void);
int libvlc_media_set_meta(void);
int libvlc_media_set_state(void);
int libvlc_media_set_user_data(void);
int libvlc_media_subitems(void);
int libvlc_media_tracks_get(void);
int libvlc_media_tracks_release(void);
int libvlc_new(void);
int libvlc_playlist_play(void);
int libvlc_release(void);
int libvlc_renderer_item_name(void);
int libvlc_renderer_item_type(void);
int libvlc_renderer_item_icon_uri(void);
int libvlc_renderer_item_flags(void);
int libvlc_renderer_discoverer_event_manager(void);
int libvlc_renderer_discoverer_list_get(void);
int libvlc_renderer_discoverer_list_release(void);
int libvlc_renderer_discoverer_new(void);
int libvlc_renderer_discoverer_release(void);
int libvlc_renderer_discoverer_start(void);
int libvlc_renderer_discoverer_stop(void);
int libvlc_retain(void);
int libvlc_set_fullscreen(void);
int libvlc_set_log_verbosity(void);
int libvlc_set_user_agent(void);
int libvlc_set_app_id(void);
int libvlc_title_descriptions_release(void);
int libvlc_toggle_fullscreen(void);
int libvlc_toggle_teletext(void);
int libvlc_track_description_release(void);
int libvlc_track_description_list_release(void);
int libvlc_video_get_adjust_float(void);
int libvlc_video_get_adjust_int(void);
int libvlc_video_get_aspect_ratio(void);
int libvlc_video_get_chapter_description(void);
int libvlc_video_get_crop_geometry(void);
int libvlc_video_get_size(void);
int libvlc_video_get_height(void);
int libvlc_video_get_cursor(void);
int libvlc_video_get_logo_int(void);
int libvlc_video_get_marquee_int(void);
int libvlc_video_get_marquee_string(void);
int libvlc_video_get_scale(void);
int libvlc_video_get_spu(void);
int libvlc_video_get_spu_count(void);
int libvlc_video_get_spu_delay(void);
int libvlc_video_get_spu_description(void);
int libvlc_video_get_teletext(void);
int libvlc_video_get_title_description(void);
int libvlc_video_get_track(void);
int libvlc_video_get_track_count(void);
int libvlc_video_get_track_description(void);
int libvlc_video_get_width(void);
int libvlc_video_set_adjust_float(void);
int libvlc_video_set_adjust_int(void);
int libvlc_video_set_aspect_ratio(void);
int libvlc_video_set_callbacks(void);
int libvlc_video_set_crop_geometry(void);
int libvlc_video_set_deinterlace(void);
int libvlc_video_set_format(void);
int libvlc_video_set_format_callbacks(void);
int libvlc_video_set_key_input(void);
int libvlc_video_set_logo_int(void);
int libvlc_video_set_logo_string(void);
int libvlc_video_set_marquee_int(void);
int libvlc_video_set_marquee_string(void);
int libvlc_video_set_mouse_input(void);
int libvlc_video_set_scale(void);
int libvlc_video_set_spu(void);
int libvlc_video_set_spu_delay(void);
int libvlc_video_set_subtitle_file(void);
int libvlc_video_set_teletext(void);
int libvlc_video_set_track(void);
int libvlc_video_take_snapshot(void);
int libvlc_video_new_viewpoint(void);
int libvlc_video_update_viewpoint(void);
int libvlc_vlm_add_broadcast(void);
int libvlc_vlm_add_vod(void);
int libvlc_vlm_add_input(void);
int libvlc_vlm_change_media(void);
int libvlc_vlm_del_media(void);
int libvlc_vlm_get_event_manager(void);
int libvlc_vlm_get_media_instance_length(void);
int libvlc_vlm_get_media_instance_position(void);
int libvlc_vlm_get_media_instance_rate(void);
int libvlc_vlm_get_media_instance_time(void);
int libvlc_vlm_pause_media(void);
int libvlc_vlm_play_media(void);
int libvlc_vlm_release(void);
int libvlc_vlm_seek_media(void);
int libvlc_vlm_set_enabled(void);
int libvlc_vlm_set_input(void);
int libvlc_vlm_set_loop(void);
int libvlc_vlm_set_mux(void);
int libvlc_vlm_set_output(void);
int libvlc_vlm_show_media(void);
int libvlc_vlm_stop_media(void);
int libvlc_set_exit_handler(void);
int libvlc_wait(void);
int libvlc_audio_filter_list_get(void);
int libvlc_video_filter_list_get(void);
int libvlc_module_description_list_release(void);

const void *libvlc_functions[] = {
 libvlc_errmsg,
 libvlc_clearerr,
 libvlc_printerr,
 libvlc_vprinterr,
 libvlc_add_intf,
 libvlc_audio_equalizer_get_amp_at_index,
 libvlc_audio_equalizer_get_band_count,
 libvlc_audio_equalizer_get_band_frequency,
 libvlc_audio_equalizer_get_preamp,
 libvlc_audio_equalizer_get_preset_count,
 libvlc_audio_equalizer_get_preset_name,
 libvlc_audio_equalizer_new,
 libvlc_audio_equalizer_new_from_preset,
 libvlc_audio_equalizer_release,
 libvlc_audio_equalizer_set_amp_at_index,
 libvlc_audio_equalizer_set_preamp,
 libvlc_audio_output_device_count,
 libvlc_audio_output_device_get,
 libvlc_audio_output_device_enum,
 libvlc_audio_output_device_id,
 libvlc_audio_output_device_list_get,
 libvlc_audio_output_device_list_release,
 libvlc_audio_output_device_longname,
 libvlc_audio_output_device_set,
 libvlc_audio_output_get_device_type,
 libvlc_audio_output_list_get,
 libvlc_audio_output_list_release,
 libvlc_audio_output_set,
 libvlc_audio_output_set_device_type,
 libvlc_audio_get_channel,
 libvlc_audio_get_delay,
 libvlc_audio_get_mute,
 libvlc_audio_get_track,
 libvlc_audio_get_track_count,
 libvlc_audio_get_track_description,
 libvlc_audio_get_volume,
 libvlc_audio_set_channel,
 libvlc_audio_set_delay,
 libvlc_audio_set_mute,
 libvlc_audio_set_track,
 libvlc_audio_set_volume,
 libvlc_audio_toggle_mute,
 libvlc_audio_set_format,
 libvlc_audio_set_format_callbacks,
 libvlc_audio_set_callbacks,
 libvlc_audio_set_volume_callback,
 libvlc_chapter_descriptions_release,
 libvlc_clock,
 libvlc_dialog_dismiss,
 libvlc_dialog_get_context,
 libvlc_dialog_post_action,
 libvlc_dialog_post_login,
 libvlc_dialog_set_callbacks,
 libvlc_dialog_set_context,
 libvlc_event_attach,
 libvlc_event_detach,
 libvlc_event_type_name,
 libvlc_free,
 libvlc_get_changeset,
 libvlc_get_compiler,
 libvlc_get_fullscreen,
 libvlc_get_input_thread,
 libvlc_get_log_verbosity,
 libvlc_get_version,
 libvlc_log_get_context,
 libvlc_log_get_object,
 libvlc_log_set,
 libvlc_log_set_file,
 libvlc_log_unset,
 libvlc_log_clear,
 libvlc_log_close,
 libvlc_log_count,
 libvlc_log_get_iterator,
 libvlc_log_iterator_free,
 libvlc_log_iterator_has_next,
 libvlc_log_iterator_next,
 libvlc_log_open,
 libvlc_media_add_option,
 libvlc_media_add_option_flag,
 libvlc_media_discoverer_event_manager,
 libvlc_media_discoverer_is_running,
 libvlc_media_discoverer_localized_name,
 libvlc_media_discoverer_media_list,
 libvlc_media_discoverer_new,
 libvlc_media_discoverer_new_from_name,
 libvlc_media_discoverer_release,
 libvlc_media_discoverer_list_get,
 libvlc_media_discoverer_list_release,
 libvlc_media_discoverer_start,
 libvlc_media_discoverer_stop,
 libvlc_media_duplicate,
 libvlc_media_event_manager,
 libvlc_media_get_codec_description,
 libvlc_media_get_duration,
 libvlc_media_get_meta,
 libvlc_media_get_mrl,
 libvlc_media_get_state,
 libvlc_media_get_stats,
 libvlc_media_get_type,
 libvlc_media_get_user_data,
 libvlc_media_get_tracks_info,
 libvlc_media_is_parsed,
 libvlc_media_get_parsed_status,
 libvlc_media_library_load,
 libvlc_media_library_media_list,
 libvlc_media_library_new,
 libvlc_media_library_release,
 libvlc_media_library_retain,
 libvlc_media_list_add_file_content,
 libvlc_media_list_add_media,
 libvlc_media_list_count,
 libvlc_media_list_event_manager,
 libvlc_media_list_index_of_item,
 libvlc_media_list_insert_media,
 libvlc_media_list_is_readonly,
 libvlc_media_list_item_at_index,
 libvlc_media_list_lock,
 libvlc_media_list_media,
 libvlc_media_list_new,
 libvlc_media_list_player_event_manager,
 libvlc_media_list_player_get_media_player,
 libvlc_media_list_player_get_state,
 libvlc_media_list_player_is_playing,
 libvlc_media_list_player_new,
 libvlc_media_list_player_next,
 libvlc_media_list_player_pause,
 libvlc_media_list_player_play,
 libvlc_media_list_player_play_item,
 libvlc_media_list_player_play_item_at_index,
 libvlc_media_list_player_previous,
 libvlc_media_list_player_release,
 libvlc_media_list_player_retain,
 libvlc_media_list_player_set_media_list,
 libvlc_media_list_player_set_media_player,
 libvlc_media_list_player_set_playback_mode,
 libvlc_media_list_player_stop,
 libvlc_media_list_release,
 libvlc_media_list_remove_index,
 libvlc_media_list_retain,
 libvlc_media_list_set_media,
 libvlc_media_list_unlock,
 libvlc_media_new_callbacks,
 libvlc_media_new_fd,
 libvlc_media_new_location,
 libvlc_media_new_path,
 libvlc_media_new_as_node,
 libvlc_media_new_from_input_item,
 libvlc_media_parse,
 libvlc_media_parse_async,
 libvlc_media_parse_with_options,
 libvlc_media_parse_stop,
 libvlc_media_player_add_slave,
 libvlc_media_player_can_pause,
 libvlc_media_player_program_scrambled,
 libvlc_media_player_next_frame,
 libvlc_media_player_event_manager,
 libvlc_media_player_get_agl,
 libvlc_media_player_get_chapter,
 libvlc_media_player_get_chapter_count,
 libvlc_media_player_get_chapter_count_for_title,
 libvlc_media_player_get_fps,
 libvlc_media_player_get_full_chapter_descriptions,
 libvlc_media_player_get_full_title_descriptions,
 libvlc_media_player_get_hwnd,
 libvlc_media_player_get_length,
 libvlc_media_player_get_media,
 libvlc_media_player_get_nsobject,
 libvlc_media_player_get_position,
 libvlc_media_player_get_rate,
 libvlc_media_player_get_role,
 libvlc_media_player_get_state,
 libvlc_media_player_get_time,
 libvlc_media_player_get_title,
 libvlc_media_player_get_title_count,
 libvlc_media_player_get_xwindow,
 libvlc_media_player_has_vout,
 libvlc_media_player_is_seekable,
 libvlc_media_player_is_playing,
 libvlc_media_player_new,
 libvlc_media_player_new_from_media,
 libvlc_media_player_next_chapter,
 libvlc_media_player_set_pause,
 libvlc_media_player_pause,
 libvlc_media_player_play,
 libvlc_media_player_previous_chapter,
 libvlc_media_player_release,
 libvlc_media_player_retain,
 libvlc_media_player_set_agl,
 libvlc_media_player_set_android_context,
 libvlc_media_player_set_chapter,
 libvlc_media_player_set_equalizer,
 libvlc_media_player_set_evas_object,
 libvlc_media_player_set_hwnd,
 libvlc_media_player_set_media,
 libvlc_media_player_set_nsobject,
 libvlc_media_player_set_position,
 libvlc_media_player_set_rate,
 libvlc_media_player_set_role,
 libvlc_media_player_set_time,
 libvlc_media_player_set_title,
 libvlc_media_player_set_xwindow,
 libvlc_media_player_stop,
 libvlc_media_player_will_play,
 libvlc_media_player_navigate,
 libvlc_media_player_set_video_title_display,
 libvlc_media_release,
 libvlc_media_retain,
 libvlc_media_save_meta,
 libvlc_media_slaves_add,
 libvlc_media_slaves_clear,
 libvlc_media_slaves_get,
 libvlc_media_slaves_release,
 libvlc_media_set_meta,
 libvlc_media_set_state,
 libvlc_media_set_user_data,
 libvlc_media_subitems,
 libvlc_media_tracks_get,
 libvlc_media_tracks_release,
 libvlc_new,
 libvlc_playlist_play,
 libvlc_release,
 libvlc_renderer_item_name,
 libvlc_renderer_item_type,
 libvlc_renderer_item_icon_uri,
 libvlc_renderer_item_flags,
 libvlc_renderer_discoverer_event_manager,
 libvlc_renderer_discoverer_list_get,
 libvlc_renderer_discoverer_list_release,
 libvlc_renderer_discoverer_new,
 libvlc_renderer_discoverer_release,
 libvlc_renderer_discoverer_start,
 libvlc_renderer_discoverer_stop,
 libvlc_retain,
 libvlc_set_fullscreen,
 libvlc_set_log_verbosity,
 libvlc_set_user_agent,
 libvlc_set_app_id,
 libvlc_title_descriptions_release,
 libvlc_toggle_fullscreen,
 libvlc_toggle_teletext,
 libvlc_track_description_release,
 libvlc_track_description_list_release,
 libvlc_video_get_adjust_float,
 libvlc_video_get_adjust_int,
 libvlc_video_get_aspect_ratio,
 libvlc_video_get_chapter_description,
 libvlc_video_get_crop_geometry,
 libvlc_video_get_size,
 libvlc_video_get_height,
 libvlc_video_get_cursor,
 libvlc_video_get_logo_int,
 libvlc_video_get_marquee_int,
 libvlc_video_get_marquee_string,
 libvlc_video_get_scale,
 libvlc_video_get_spu,
 libvlc_video_get_spu_count,
 libvlc_video_get_spu_delay,
 libvlc_video_get_spu_description,
 libvlc_video_get_teletext,
 libvlc_video_get_title_description,
 libvlc_video_get_track,
 libvlc_video_get_track_count,
 libvlc_video_get_track_description,
 libvlc_video_get_width,
 libvlc_video_set_adjust_float,
 libvlc_video_set_adjust_int,
 libvlc_video_set_aspect_ratio,
 libvlc_video_set_callbacks,
 libvlc_video_set_crop_geometry,
 libvlc_video_set_deinterlace,
 libvlc_video_set_format,
 libvlc_video_set_format_callbacks,
 libvlc_video_set_key_input,
 libvlc_video_set_logo_int,
 libvlc_video_set_logo_string,
 libvlc_video_set_marquee_int,
 libvlc_video_set_marquee_string,
 libvlc_video_set_mouse_input,
 libvlc_video_set_scale,
 libvlc_video_set_spu,
 libvlc_video_set_spu_delay,
 libvlc_video_set_subtitle_file,
 libvlc_video_set_teletext,
 libvlc_video_set_track,
 libvlc_video_take_snapshot,
 libvlc_video_new_viewpoint,
 libvlc_video_update_viewpoint,
 libvlc_vlm_add_broadcast,
 libvlc_vlm_add_vod,
 libvlc_vlm_add_input,
 libvlc_vlm_change_media,
 libvlc_vlm_del_media,
 libvlc_vlm_get_event_manager,
 libvlc_vlm_get_media_instance_length,
 libvlc_vlm_get_media_instance_position,
 libvlc_vlm_get_media_instance_rate,
 libvlc_vlm_get_media_instance_time,
 libvlc_vlm_pause_media,
 libvlc_vlm_play_media,
 libvlc_vlm_release,
 libvlc_vlm_seek_media,
 libvlc_vlm_set_enabled,
 libvlc_vlm_set_input,
 libvlc_vlm_set_loop,
 libvlc_vlm_set_mux,
 libvlc_vlm_set_output,
 libvlc_vlm_show_media,
 libvlc_vlm_stop_media,
 libvlc_set_exit_handler,
 libvlc_wait,
 libvlc_audio_filter_list_get,
 libvlc_video_filter_list_get,
 libvlc_module_description_list_release,
 NULL
};

